# Generated by Django 4.2.19 on 2025-02-11 15:59

import EmpresaPago.validadores
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[EmpresaPago.validadores.validar_cedula])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, validators=[EmpresaPago.validadores.validar_telefono])),
                ('tipo', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Ventas', 'Ventas'), ('Gerencia', 'Gerencia'), ('Otro', 'Otro')], max_length=50)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Salarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bono', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salario', to='EmpresaPago.empleados')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'db_table': 'Salarios',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_registro', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Permiso', 'Permiso'), ('Vacaciones', 'Vacaciones'), ('Incapacidad', 'Incapacidad')], max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='EmpresaPago.empleados')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'Registros',
            },
        ),
    ]
